services:
  - type: web
    name: synthese-francais
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    region: frankfurt
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSLMODE
        value: require
      - key: DATABASE_SCHEMA
        value: app_private
      - key: COOKIE_SECURE
        value: "true"
      - key: DEMO_MODE
        value: "false"
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_FULL_NAME
        value: Administrateur
      - key: ADMIN_PASSWORD
        sync: false
      - key: TEACHER_USERNAME
        value: prof.francais
      - key: TEACHER_FULL_NAME
        value: Professeur de francais
      - key: TEACHER_PASSWORD
        sync: false
